### ISSUE TITLE
Vanilla items is not working

### ISSUE THREAD

**Issue by Breper0612** [jummes/MoreCompost#12]
I'd like to report a bug in the MoreCompost plugin.
The following items are no longer allowed in the composter.

・Nether Wart
・Weeping/Twisting Vines
・Nether Sprouts
・Fungi
・Roots
・Nether/Warped Wart Block

Sorry for my bad English.

https://minecraft.gamepedia.com/Composter

**Comment by ZamponiMarco** [comment]
Hi breber, thanks for your submission
I'll add them pretty soon!

**Comment by Breper0612** [comment]
Thanks for support
