### ISSUE TITLE
Still not working vanilla items

### ISSUE THREAD

**Issue by Breper0612** [jummes/MoreCompost#13]
Thank you for your quick response the other day.

But part of items still no longer allowed in the composter.
・Roots (minecraft:warped_roots and minecraft:crimson_roots)
Please to fix this bug again.

Sorry for my bad English.

https://minecraft.gamepedia.com/Composter
https://minecraft.gamepedia.com/Roots

**Comment by ZamponiMarco** [comment]
Does the other ones work from the fix?

**Comment by Breper0612** [comment]
Yes, other items is working normally.
I use morecomposter-2.1.7

**Comment by ZamponiMarco** [comment]
Should be fixed in the last version i just updated

**Comment by Breper0612** [comment]
It was fixed in 2.1.8
sorry
