### ISSUE TITLE
Permission for player

### ISSUE THREAD

**Issue by GripyCZ** [jummes/MoreCompost#2]
Hi, I need help I can't allow players to compost. they cannot compost my own added item and I would like to ask if I need any right - Gripy

**Comment by GripyCZ** [comment]
*permission

**Comment by ZamponiMarco** [comment]
I'm adding some details on the docs about this

**Comment by ZamponiMarco** [comment]
I've added the permission section in the wiki, you can see it here
https://github.com/ZamponiMarco/MoreCompost/wiki#permissions
If it isn't enough let me know, if it's well explained i can close the issue

**Comment by ZamponiMarco** [comment]
I assume the problem is solved, closing
