### ISSUE TITLE
Deserialization of items without version or with wrong version fails 

### ISSUE THREAD

**Issue by ZamponiMarco** [jummes/MoreCompost#4]
Unfortunately, updating wiped all items from the GUI.

My compostable file was:
https://hastebin.com/lihaxukefo.shell
However, the GUI was not loading these items.
And now after updating, the compostable file is:
https://hastebin.com/yunohayuqa.shell
And the GUI shows neither the items in the file nor the items I added in game before updating.

_Originally posted by @Toadby in https://github.com/ZamponiMarco/MoreCompost/issues/3#issuecomment-593197777_

**Comment by ZamponiMarco** [comment]
So, basically the item **v** attribute is server version dependant, and it describes the version of the item to serialize, if it's higher than a certain value it won't work, and it's not equal for every item, for now i can tell you a workaround, just set all the versions to 1, then the correct versions will be correctly put in the attribute automatically by the plugin, I leave this issue open however because i want to find a way to avoid this problem

In addition to that, the yaml library provided by bukkit doesn't allow the use of comments in the middle of the file outside config.yml (i know it's stupid, they work only as an header), so every little modific that you do will wipe out all your comments in the middle of the file, so you should just put them all at the top

Additionally, I add this compostabletable.yml https://hastebin.com/mosukufani.shell, that it's your yml file with the item versions set to 1, this should work properly now, just be careful with comments

**Comment by Toadby** [comment]
Hi! I updated the config as you said, moving comments to the top and changing v to 1. Loading it in game (and doing /mc reload), the items still don't show in the GUI and no longer seem to be working at all. The "v" did not autocorrect to another value, and `ItemStackWrapper` once again auto-corrected to `com.github.jummes.morecompost.libs.model.wrapper.ItemStackWrapper`.

**Comment by ZamponiMarco** [comment]
/mc reload doesn't force the serializatiob, try to edit just one value fron the gui

The correction is intended, i added it in 2.0.1 cause the precedent version gave compatibility issues with some other plugins

**Comment by Toadby** [comment]
There are no items in the GUI. Do you mean add a list and compostable? I don't want to overwrite the ones I have by making one of the same name.

**Comment by Toadby** [comment]
Creating a compostable table in the GUI wipes the table I created from the text file. Adding a value, editing the config to add the other values I want, and editing the value in the GUI only wipes the config again to include the updated GUI item.

**Comment by ZamponiMarco** [comment]
That's bizarre, from my end everything worked well and i don't still understand where the problem could be actually

**Comment by Toadby** [comment]
Would it be possible to add a command to reload from the text file? I have an appointment in a minute but I can keep looking into this when I get home from that!

**Comment by ZamponiMarco** [comment]
Yeah, i might add that too to help using text editors, unfortunately i didn't work much on the text editor because i thought noone would have use it so sorry for.these bugs

**Comment by Toadby** [comment]
No worries! I Personally much prefer the text editor but I understand that that's personal preference :) I would love to see it working better but don't worry too much about it ! I dont want to overwork you :P

**Comment by ZamponiMarco** [comment]
This compostabletable.yml (https://hastebin.com/otukutogep.shell) worked perfectly to me in paper-129 in 1.15.2, MoreCompost version 2.0.3 

I just did what i said here to get this file:
>  just set all the versions to 1, then the correct versions will be correctly put in the attribute automatically by the plugin

**Comment by Toadby** [comment]
> Hi! I updated the config as you said, moving comments to the top and changing v to 1. Loading it in game (and doing /mc reload), the items still don't show in the GUI and no longer seem to be working at all. The "v" did not autocorrect to another value, and `ItemStackWrapper` once again auto-corrected to `com.github.jummes.morecompost.libs.model.wrapper.ItemStackWrapper`.

Sorry for the duplicate. I guess I said before, but this wasn't working for me. BUT it turns out I had two versions installed at once 😅 My bad for the double post and the user error - just bad memory on my part! I have removed both old jars and updated to 2.0.3 to try again.
V is still set to 1 on all items, but I can compost them just fine. Thank you for your patience and sorry again :')

**Comment by ZamponiMarco** [comment]
No problem, i close the issue and i create a new one for enhancing the writing on text editors
